# Generated by Django 3.2.25 on 2024-04-27 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopcontact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'پیام', 'verbose_name_plural': 'پیام ها'},
        ),
    ]
