# Generated by Django 3.2.25 on 2024-04-28 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoporders', '0003_alter_order_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ref_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='شماره پیگیری تراکنش'),
        ),
    ]
