# Generated by Django 3.2.25 on 2024-04-26 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopproducts', '0002_auto_20240426_1155'),
        ('shop_products_category', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='ProductCategory',
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name': 'دسته بندی', 'verbose_name_plural': 'دسته بندی ها'},
        ),
    ]
