# Generated by Django 3.2.25 on 2024-04-27 07:04

from django.db import migrations, models
import shop_slider.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_slider', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=shop_slider.models.upload_image_path, verbose_name='تصویر'),
        ),
    ]
