# Generated by Django 3.2.25 on 2024-04-27 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopsetting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopsetting',
            name='aboutus',
            field=models.TextField(blank=True, null=True, verbose_name='درباره ما'),
        ),
    ]
