# Generated by Django 3.2.25 on 2024-04-26 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_products_category', '0002_auto_20240426_1302'),
        ('shopproducts', '0002_auto_20240426_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(blank=True, to='shop_products_category.ProductCategory', verbose_name='دسته بندی'),
        ),
    ]
