# Generated by Django 3.2.25 on 2024-04-27 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopproducts', '0005_auto_20240427_1112'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgallery',
            options={'verbose_name': 'گالری تصاویر', 'verbose_name_plural': 'گالری تصاویر'},
        ),
    ]
