# Generated by Django 3.2.25 on 2024-04-28 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopproducts', '0006_alter_productgallery_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='visit_count',
            field=models.IntegerField(default=0, verbose_name='تعداد مشاهده'),
        ),
    ]
